# Generated by Django 3.2.8 on 2021-10-21 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoParkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{,20}$', 'Name must be A-Z,a-z,max_length=20')])),
            ],
            options={
                'db_table': 'auto_park',
            },
        ),
    ]
