# Generated by Django 3.2.8 on 2021-10-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'cars',
            },
        ),
        migrations.RenameField(
            model_name='computermodel',
            old_name='year',
            new_name='chipset',
        ),
        migrations.AlterModelTable(
            name='computermodel',
            table=None,
        ),
    ]
