# Generated by Django 3.2.8 on 2021-10-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0002_auto_20211019_1538'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='computermodel',
            table='computers',
        ),
    ]
