# Generated by Django 3.2.8 on 2021-10-23 18:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_park', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{,20}$', 'Brand must be A-Z, 0-9, max-length=20')])),
                ('model', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{,20}$', 'Model must be A-Z, a-z, 0-9, max-length=20')])),
                ('color', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-z]{,20}$', 'Color must be a-z,max-length=20')])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2021)])),
                ('autoPark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='auto_park.autoparkmodel')),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
