# Generated by Django 3.2.8 on 2021-10-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20211027_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'ordering': ('id',)},
        ),
    ]
